VS ApexCode/UlbergProject0/force-app/main/default/objects/Checkout__c/Checkout__c.object-meta.xml
<CustomObject>
    <label>Checkout</label>
    <nameField>
        <displayFormat>CO-{0000000}</displayFormat>
        <label>Checkout Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checkout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Checkout__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <label>Full Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Checkout__c/fields/Is_US_Address__c.field-meta.xml
<CustomField>
    <fullName>Is_US_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is US Address</label>
    <type>Checkbox</type>
</CustomField>

VS ApexCode/UlbergProject0/force-app/main/default/classes/DanEditInitializerExtension.cls
//copy of Rayshawn Initializer Extension for the checkout page.  Just in case needed to make last minute changes as Rayshawn was testing his code.
public with sharing class DanEditInitializerExtension {
  private final Checkout__c checkO;
  Integer total;

  public DanEditInitializerExtension(DanEditCheckoutController controller) {
    this.checkO = (Checkout__c) controller.getCheckout();
  }
  public String getGreeting() {
    return checkO.full_name__c + ' Shipping Information';
  }
  public String getCardInfo() {
    return checkO.full_name__c + ' Billing Information';
  }
  public void setUSAddress() {
    checkO.is_us_address__c = true;
    update checkO;
  }
}