VS ApexCode/UlbergProject0/force-app/main/default/objects/Checkout__c/Checkout__c.object-meta.xml
<CustomObject>
    <label>Checkout</label>
    <nameField>
        <displayFormat>CO-{0000000}</displayFormat>
        <label>Checkout Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checkout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Checkout__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Checkout__c/fields/Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Number__c</fullName>
    <label>Card Number</label>
    <length>19</length>
    <maskChar>X</maskChar>
    <maskType>creditCard</maskType>
    <type>EncryptedText</type>
</CustomField>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Checkout__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Checkout__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Checkout__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <label>Full Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Checkout__c/fields/Is_US_Address__c.field-meta.xml
<CustomField>
    <fullName>Is_US_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is US Address</label>
    <type>Checkbox</type>
</CustomField>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Checkout__c/fields/Items_In_Cart__c.field-meta.xml
<CustomField>
    <fullName>Items_In_Cart__c</fullName>
    <label>Items In Cart</label>
    <summaryForeignKey>Shopping_Cart__c.Checkout__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Checkout__c/fields/Name_On_Card__c.field-meta.xml
<CustomField>
    <fullName>Name_On_Card__c</fullName>
    <label>Name On Card</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Checkout__c/fields/Security_Code__c.field-meta.xml
<CustomField>
    <fullName>Security_Code__c</fullName>
    <label>Security Code</label>
    <length>3</length>
    <maskChar>X</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Checkout__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Is_US_Address__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>US_State_Abbreviations</valueSetName>
    </valueSet>
</CustomField>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Checkout__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Product2/fields/Asking_Price__c.field-meta.xml
<CustomField>
    <fullName>Asking_Price__c</fullName>
    <label>Asking Price</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Shopping_Cart__c/Shopping_Cart__c.object-meta.xml
<CustomObject>
    <label>Shopping Cart</label>
    <nameField>
        <displayFormat>SO-{0000000}</displayFormat>
        <label>Shopping Cart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shopping Carts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Shopping_Cart__c/fields/Checkout__c.field-meta.xml
<CustomField>
    <fullName>Checkout__c</fullName>
    <label>Checkout</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$User.Id</field>
            <operation>equals</operation>
            <valueField>Checkout__c.CreatedBy.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Checkout__c</referenceTo>
    <relationshipLabel>Cart</relationshipLabel>
    <relationshipName>Cart</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Shopping_Cart__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cart</relationshipLabel>
    <relationshipName>Cart_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

VS ApexCode/UlbergProject0/force-app/main/default/globalValueSets/US_State_Abbreviations.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>NV</fullName>
    </customValue>
    <customValue>
        <fullName>NH</fullName>
    </customValue>
    <masterLabel>US State Abbreviations</masterLabel>
</GlobalValueSet>

VS ApexCode/UlbergProject0/force-app/main/default/classes/checkoutController.cls
public with sharing class checkoutController {
  private Checkout__c Chout;
  private List<Shopping_Cart__c> shoppingCart = new List<Shopping_Cart__c>();
  private Boolean needNewItem = false;
  private Shopping_Cart__c newItem;

  public checkoutController() {
    Chout = [
      SELECT
        id,
        Full_Name__c,
        Address__c,
        City__c,
        State__c,
        Zip_Code__c,
        Is_US_Address__c,
        Card_Number__c,
        Name_On_Card__c,
        Expiration_Date__c,
        Security_Code__c,
        Items_In_Cart__c
      FROM Checkout__c
      WHERE id = :apexPages.currentPage().getParameters().get('id')
    ];

    shoppingCart = [
      SELECT
        id,
        Checkout__r.id,
        Checkout__r.name,
        Product__r.name,
        Product__r.Asking_Price__c
      FROM Shopping_Cart__c
      WHERE Checkout__r.id = :Chout.id
    ];
  }
  //variable accessors
  public Checkout__c getCheckout() {
    return Chout;
  }
  public List<Shopping_Cart__c> getShoppingCart() {
    return shoppingCart;
  }
  public Shopping_Cart__c getNewItem() {
    return newItem;
  }
  public Boolean getNeedNewItem() {
    return needNewItem;
  }

  //save data and refresh page with new settings
  public PageReference save() {
    PageReference newChoutPage = Page.CheckoutPage;
    if (newChoutPage == null) {
      newChoutPage = Page.CheckoutPage;
      newChoutPage.getParameters().put('error', 'noParam');
    } else {
      try {
        update Chout;
        needNewItem = false;
        newChoutPage = new PageReference(
          '/apex/CheckoutPage?id=' +
          Chout.id +
          '&key=false'
        );
      } catch (Exception e) {
        newChoutPage = Page.CheckoutPage;
        newChoutPage.getParameters().put('error', 'noInsert');
      }
    }
    newChoutPage.setRedirect(true);
    return newChoutPage;
  }
  //clears input fields
  public PageReference cancel() {
    return null;
  }
  //saves new item to database and updates tables
  public PageReference addToCart() {
    insert newItem;
    update Chout;
    update shoppingCart;
    needNewItem = false;
    return null;
  }
  //instantiate new shopping cart and associate it with parent Chout
  //update table
  public PageReference newCart() {
    if (newItem == null)
      newItem = new Shopping_Cart__c();
    newItem.Checkout__c = Chout.id;
    needNewItem = true;
    update Chout;
    return null;
  }
  //refresh page with current values and allow access for record changes
  public PageReference updateInfo() {
    PageReference newChoutPage = new PageReference(
      '/apex/CheckoutPage?id=' +
      Chout.id +
      '&key=true'
    );
    newChoutPage.setRedirect(true);
    return newChoutPage;
  }
}