VS ApexCode/UlbergProject0/force-app/main/default/objects/Checkout__c/Checkout__c.object-meta.xml
<CustomObject>
    <label>Checkout</label>
    <nameField>
        <displayFormat>CO-{0000000}</displayFormat>
        <label>Checkout Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checkout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Checkout__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <label>Full Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

VS ApexCode/UlbergProject0/force-app/main/default/classes/ProductDetailExtensionContorllerTest.cls
@isTest
public class ProductDetailExtensionContorllerTest {
  @TestSetup
  public static void setupData() {
    Checkout__c chout = new Checkout__c();
    chout.Full_Name__c = Userinfo.getFirstName() + ' ' + Userinfo.getLastName();
    insert chout;

    Product2 pdct = new Product2();
    pdct.Name = 'Test';
    insert pdct;
  }

  @isTest
  public static void TP_addToCart() {
    Product2 pdct = (Product2) [SELECT Id, Name FROM Product2 LIMIT 1];
    PageReference pageRef = new PageReference(
      '/apex/ProductDetailPage?id=' +
      pdct.Id +
      '&key=false'
    );
    Test.setCurrentPage(pageRef);

    System.debug(pageRef);

    // need a way to insert the product ID to the page param
    Test.startTest();
    //ProductDetailPageExtensionController pdpc = new ProductDetailPageExtensionController();
    //pdpc.addToCart();

    System.assert(true);

    Test.stopTest();
  }
}