VS ApexCode/UlbergProject0/force-app/main/default/objects/Checkout__c/Checkout__c.object-meta.xml
<CustomObject>
    <label>Checkout</label>
    <nameField>
        <displayFormat>CO-{0000000}</displayFormat>
        <label>Checkout Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checkout</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Shopping_Cart__c/Shopping_Cart__c.object-meta.xml
<CustomObject>
    <label>Shopping Cart</label>
    <nameField>
        <displayFormat>SO-{0000000}</displayFormat>
        <label>Shopping Cart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shopping Carts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Shopping_Cart__c/fields/Checkout__c.field-meta.xml
<CustomField>
    <fullName>Checkout__c</fullName>
    <label>Checkout</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$User.Id</field>
            <operation>equals</operation>
            <valueField>Checkout__c.CreatedBy.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Checkout__c</referenceTo>
    <relationshipLabel>Cart</relationshipLabel>
    <relationshipName>Cart</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

VS ApexCode/UlbergProject0/force-app/main/default/classes/CheckoutControllerTests.cls
//An existing table is required to run the CheckoutPage
@isTest(SeeAllData=true)
public class CheckoutControllerTests {
  //Set page for test
  @isTest
  public static void testCheckoutController() {
    PageReference pageRef = new PageReference(
      '/apex/CheckoutPage?id=a005e0000067NsdAAE&key=false'
    );
    Test.setCurrentPage(pageRef);
    //verify the correct page is displayed
    System.debug(pageRef);
    //Instatiate CheckoutController and assign url
    CheckoutController controller = new CheckoutController();
    String nextPage = controller.save().getUrl();

    //Verify current page
    System.debug(nextPage);

    nextPage = controller.save().getUrl();

    //Add parameters to page URL
    ApexPages.currentPage().getParameters().put('id', 'a005e0000067NsdAAE');
    System.debug(pageRef);
    System.debug(nextPage);

    //Instantiate a new controller with all parameters in the page
    controller = new CheckoutController();

    Checkout__c newRecord = controller.getCheckout();
    List<Shopping_Cart__c> newShoppingList = controller.getShoppingCart();

    for (Shopping_Cart__c test : newShoppingList) {
      System.assertEquals(newRecord.id, test.Checkout__r.id);
    }
    Boolean bin = controller.getNeedNewItem();
    System.assertEquals(false, bin);

    nextPage = controller.save().getUrl();
    System.assertEquals(false, controller.getNeedNewItem());

    // Verify that the success page displays
    System.assertEquals(
      '/apex/CheckoutPage?id=' +
      newRecord.id +
      '&key=false',
      nextPage
    );
    System.debug(nextPage);

    controller.updateInfo();
    nextPage = controller.updateInfo().getUrl();
    System.assertEquals(
      '/apex/CheckoutPage?id=' +
      newRecord.id +
      '&key=true',
      nextPage
    );
    System.debug(nextPage);

    controller.newCart();
    Shopping_Cart__c nItem = controller.getNewItem();
    System.debug(nItem);

    System.assertEquals(true, controller.getNeedNewItem());
    System.debug(controller.getNeedNewItem());

    System.assertEquals(newRecord.id, nItem.Checkout__c);
    System.debug(nItem.Checkout__c);

    controller.addToCart();
    System.assertEquals(false, controller.getNeedNewItem());
    System.debug(controller.getNeedNewItem());
  }
}