RayshawnP1/demonstrationdeploy/metadata/unpackaged/unpackaged/objects/Shop_Duty__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Check if this is an active routinely scheduled activity. Uncheck if no longer used.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the duty</description>
        <inlineHelpText>a short description of the duty requirements</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Duty_Days__c</fullName>
        <defaultValue>&apos;Monday;Tuesday;Wednesday;Thursday;Friday;Saturday;Sunday&apos;</defaultValue>
        <description>Days that the duty needs to be completed</description>
        <label>Duty Days</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                    <default>true</default>
                    <label>Tuesday</label>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shop Duty</label>
    <nameField>
        <label>Duty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shop Duties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

RayshawnP1/demonstrationdeploy/metadata/unpackaged/unpackaged/classes/ShopDutiesListApexController.cls
public class ShopDutiesListApexController {

    @AuraEnabled
    public static List<Shop_Duty__c> getItems() {
        return [SELECT Id, Name,  Description__c,  Active__c, Duty_Days__c
                FROM Shop_Duty__c];
    }
    
    @AuraEnabled
    public static Shop_Duty__c saveItem(Shop_Duty__c item) {
        // Perform isUpdateable() checking first, then
        System.debug(item);
        upsert item;
        return item;
    }
    
    @AuraEnabled
    public static Shop_Duty__c getNewItem(){
        return new Shop_Duty__c();
        
    }
}