VS ApexCode/UlbergProject0/force-app/main/default/objects/Previously_Sold_Item__c/Previously_Sold_Item__c.object-meta.xml
<CustomObject>
    <label>Previously Sold Item</label>
    <nameField>
        <label>Previously Sold Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Previously Sold Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Previously_Sold_Item__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Previously Sold Items</relationshipLabel>
    <relationshipName>Previously_Sold_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Previously_Sold_Item__c/fields/RatingNumber__c.field-meta.xml
<CustomField>
    <fullName>RatingNumber__c</fullName>
    <label>RatingNumber</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Rating__c/Rating__c.object-meta.xml
<CustomObject>
    <label>Rating</label>
    <nameField>
        <label>ItemYouAreReviewing</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Rating__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ratings</relationshipLabel>
    <relationshipName>Ratings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Rating__c/fields/Previously_Sold_Item__c.field-meta.xml
<CustomField>
    <fullName>Previously_Sold_Item__c</fullName>
    <label>Previously Sold Item</label>
    <referenceTo>Previously_Sold_Item__c</referenceTo>
    <relationshipLabel>Ratings</relationshipLabel>
    <relationshipName>Ratings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Rating__c/fields/Rating_of_item__c.field-meta.xml
<CustomField>
    <fullName>Rating_of_item__c</fullName>
    <description>1-10 scale 10 being a perfect review</description>
    <label>Rating of item</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

VS ApexCode/UlbergProject0/force-app/main/default/classes/TriggerHandler.cls
public class TriggerHandler {
    
    public static void createReview(list<Previously_Sold_Item__c> RevList) 
    {
        List<Rating__c> needReview = new List<Rating__c>();
        for(Previously_Sold_Item__c sold : RevList){
            needReview.add(CreateNewRating(sold));
            
        }   
        
        Insert needReview;
    }
    //Create new Rating
    @testVisible
    private static Rating__c CreateNewRating(Previously_Sold_Item__c SoldItem){
        Rating__C NewRating = new Rating__c();
        
        NewRating.Name= 'New Rating'+ SoldItem.Name;
        NewRating.Previously_Sold_Item__c = SoldItem.id;
        NewRating.Contact__c = SoldItem.Contact__c;
        return NewRating;
    }
   //Change value on sold item from rating object  
    public static void ChangeReview(list<Rating__c> RatList){
        
  list<Previously_Sold_Item__c> Reviewing = [Select id from Previously_Sold_Item__c];    
        for(Rating__c Rat : RatList){
     
           id prevSoldID =   Rat.Previously_Sold_Item__c;
              
                     for(Previously_Sold_Item__c Item : Reviewing){
                         if(Item.Id == prevSoldID){
                             Item.RatingNumber__c = Rat.Rating_of_item__c;
                         }
                         
                     }
        }
        update(Reviewing);

    }
    
 // Validation rule for  rating  must be between 1- 10
 
    public static void Validation(list<Rating__c> ValList){
        
        list<Rating__c> MyList =  ValList;
        
        for(Rating__c ValRat : ValList){
            
             Decimal ValInt = ValRat.Rating_of_item__c;
            if(ValInt > 10){
                ValRat.addError('Cannot go over 10');
            }
            if(ValInt < 1){
                ValRat.addError('Cannot go under 1');
            }
            
        }
     
        
    }    
    
    
    
    
}