VS ApexCode/UlbergProject0/force-app/main/default/objects/Previously_Sold_Item__c/Previously_Sold_Item__c.object-meta.xml
<CustomObject>
    <label>Previously Sold Item</label>
    <nameField>
        <label>Previously Sold Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Previously Sold Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Previously_Sold_Item__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Previously Sold Items</relationshipLabel>
    <relationshipName>Previously_Sold_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Rating__c/Rating__c.object-meta.xml
<CustomObject>
    <label>Rating</label>
    <nameField>
        <label>ItemYouAreReviewing</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Rating__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ratings</relationshipLabel>
    <relationshipName>Ratings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Rating__c/fields/Previously_Sold_Item__c.field-meta.xml
<CustomField>
    <fullName>Previously_Sold_Item__c</fullName>
    <label>Previously Sold Item</label>
    <referenceTo>Previously_Sold_Item__c</referenceTo>
    <relationshipLabel>Ratings</relationshipLabel>
    <relationshipName>Ratings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

VS ApexCode/UlbergProject0/force-app/main/default/objects/Rating__c/fields/Rating_of_item__c.field-meta.xml
<CustomField>
    <fullName>Rating_of_item__c</fullName>
    <description>1-10 scale 10 being a perfect review</description>
    <label>Rating of item</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

VS ApexCode/UlbergProject0/force-app/main/default/classes/TestHandler.cls
@isTest
public class TestHandler {
    
    public testMethod static void TestReview(){
    list<Previously_Sold_Item__c> TestingList = new list <Previously_Sold_Item__c>();
        
  TriggerHandler Handle = new TriggerHandler();
        Contact Cont = new Contact();
         //cont.Id = 'MyCont';
        cont.FirstName = 'bob';
            cont.LastName = 'smith';
        
           insert(Cont);
      
        for(Integer num = 0; num < 25; num++) {
     
            TestingList.add(New Previously_Sold_Item__c(Name = 'SoldItem' +num));
            
        }
     
      cont = [Select id, name from contact where name like 'bob%'];
        for(Previously_Sold_Item__c item: TestingList){
            item.Contact__c = Cont.Id;
             if( item.Contact__c == Cont.Id) {
            boolean result = true;
             System.assertEquals(true, result);
        }
     
            
        }
        
        
    insert(TestingList);
     

       
       
}
    public testMethod static void TestSetup2(){
        
        Contact Cont = new Contact();
         //cont.Id = 'MyCont';
        cont.FirstName = 'bob';
            cont.LastName = 'smith';
        insert(Cont);
        
        Previously_sold_item__c PrevSold = new Previously_sold_Item__c();
        PrevSold.Contact__c = cont.Id;
        prevsold.Name = 'SoldItem';
        insert(PrevSold);
        PrevSold = [Select id, name From Previously_Sold_Item__c where name like 'SoldItem' limit 1];
        
          
        Rating__c MyRat = New Rating__c();
        MyRat.Contact__c = cont.Id;
        MyRat.Previously_Sold_Item__c = PrevSold.Id;
   
        insert(MyRat);
        if(MyRat.Contact__c == cont.Id){
            boolean MyRatTrue = true;
            system.assert(True, MyRatTrue);
        }
        Myrat.Rating_of_item__c = 5;
        update(Myrat);
        
    }
    
    
    
    
    
    
    }